using SeleniumBot;

var web = new AutomationWeb();
web.CriarNovoUsuario();
web.CadastrarSenhaForaDoPadrao();
web.Aguardar3Segundos();
web.CadastrarSenhaCorreto();
web.Aguardar3Segundos();
web.ClicarExibirClientes();
web.Aguardar3Segundos();
web.FiltrarUusarios();
int ClienteSelecionado = web.SelecionarIdCliente();
web.Aguardar3Segundos();
web.VisualizarCliente(ClienteSelecionado);
web.Aguardar3Segundos();
web.ClicarExibirClientes();
web.Aguardar3Segundos();
web.ClicarAlterarStatusCliente(ClienteSelecionado);
web.Aguardar3Segundos();
web.ClicarAlterarStatusCliente(ClienteSelecionado);
//web.Aguardar3Segundos();
//web.ClicarAlterarSenha();
//web.Aguardar3Segundos();
//web.CadastrarSenhaCorreto();
web.Aguardar3Segundos();
web.ClicarExibirClientes();
web.Aguardar3Segundos();
web.CriarNovoEndereco(ClienteSelecionado);
web.Aguardar3Segundos();
web.CriarNovoCartao(ClienteSelecionado);
web.Aguardar3Segundos();
web.DeletarCartao();
web.Aguardar3Segundos();
web.DeletarEndereco();
web.Aguardar3Segundos();
web.EditarCartao();
web.Aguardar3Segundos();
web.EditarEndereco();
web.Aguardar3Segundos();
web.ClicarExibirClientes();
web.Aguardar3Segundos();
web.EditarCliente(ClienteSelecionado);

Console.WriteLine("Sucesso ao executar os testes");