USE EletronicStore;

INSERT INTO TIPOS_RESIDENCIA(TPR_TIPO) VALUES 
('CASA'), 
('APARTAMENTO'), 
('SOBRADO'), 
('KITNET'), 
('LOFT'), 
('STUDIO'), 
('FLAT'), 
('DUPLEX'), 
('TRIPLEX'), 
('COBERTURA'), 
('BANGALÔ'), 
('CHALÉ'),
('MANSÃO'), 
('FAZENDA'),
('SÍTIO'), 
('CHÁCARA'),
('VILA'),
('CONDOMÍNIO'),
('CASA GEMINADA'),
('RESIDÊNCIA TÉRREA');

INSERT INTO TIPOS_USUARIO (TPU_TIPO) VALUES 
('ADMINISTRADOR'),
('CLIENTE');

INSERT INTO TIPOS_TELEFONE (TPT_TIPO) VALUES ('Fixo'), ('Movel');

INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('AEROPORTO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('ALAMEDA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('ÁREA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('AVENIDA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('CAMPO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('CHÁCARA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('COLÔNIA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('CONDOMÍNIO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('CONJUNTO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('DISTRITO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('ESPLANADA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('ESTAÇÃO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('ESTRADA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('FAZENDA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('FEIRA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('JARDIM');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('LADEIRA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('LAGO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('LAGOA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('LARGO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('LOTEAMENTO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('NÚCLEO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('PARQUE');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('PASSARELA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('PÁTIO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('PRAÇA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('QUADRA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('RECANTO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('RESIDENCIAL');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('RODOVIA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('RUA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('SETOR');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('SITIO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('TRAVESSA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('TRECHO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('TREVO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('VALE');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('VEREDA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('VIA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('VIADUTO');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('VIELA');
INSERT INTO TIPOS_LOGRADOURO(TPL_TIPO) VALUES('VILA');

INSERT INTO GENEROS(GNR_GENERO) VALUES 
('MASCULINO'),
('FEMININO'),
('OUTRO');

INSERT INTO BANDEIRAS_CARTAO (BDC_NOME) VALUES
('VISA'),
('MASTERCARD'),
('AMERICAN EXPRESS'),
('DINERS CLUB'),
('DISCOVER'),
('UNIONPAY'),
('JCB'),
('ELO'),
('HIPERCARD');