USE EletronicStore;
GO

CREATE TRIGGER TG_VerificarPais
ON PAISES
INSTEAD OF INSERT
AS BEGIN
	IF NOT EXISTS(
		SELECT 1 FROM PAISES P
		JOIN INSERTED I ON
		P.PAS_NOME = UPPER(TRIM(I.PAS_NOME))
	)
		
	BEGIN
	INSERT INTO PAISES(PAS_NOME)
		SELECT UPPER(TRIM(I.PAS_NOME)) FROM INSERTED I
	END
END;
GO


CREATE TRIGGER TG_VerificarEstado
ON ESTADOS
INSTEAD OF INSERT
AS BEGIN
	IF NOT EXISTS(
		SELECT 1 FROM ESTADOS E
		JOIN INSERTED I ON
		E.EST_NOME = UPPER(TRIM(I.EST_NOME)) AND
		E.EST_PAS_ID = I.EST_PAS_ID
	)
		
	BEGIN
		INSERT INTO ESTADOS(EST_NOME,EST_PAS_ID)
		SELECT UPPER(TRIM(I.EST_NOME)), I.EST_PAS_ID FROM INSERTED I
	END
END;
GO


CREATE TRIGGER TG_VerifiMunicipios
ON MUNICIPIOS
INSTEAD OF INSERT
AS BEGIN
	IF NOT EXISTS(
		SELECT 1 FROM MUNICIPIOS M
		JOIN INSERTED I ON
		M.MUC_NOME = UPPER(TRIM(I.MUC_NOME)) AND
		M.MUC_EST_ID = I.MUC_EST_ID
	)
	BEGIN
		INSERT INTO MUNICIPIOS (MUC_NOME, MUC_EST_ID)
		SELECT UPPER(TRIM(I.MUC_NOME)), I.MUC_EST_ID FROM INSERTED I
	END
END;
GO


CREATE TRIGGER TG_VerificarEndereco
ON ENDERECOS
INSTEAD OF INSERT
AS BEGIN
	IF NOT EXISTS(
		SELECT 1 FROM ENDERECOS E
		JOIN INSERTED I ON 
		E.END_APELIDO = I.END_APELIDO AND
		E.END_LOGRADOURO = I.END_LOGRADOURO AND
		E.END_NUMERO = I.END_NUMERO AND
		E.END_CEP = I.END_CEP AND
		ISNULL(E.END_OBSERVACAO,'') = ISNULL(I.END_OBSERVACAO,'') AND
		E.END_BAIRRO = I.END_BAIRRO AND
		E.END_TPR_ID = I.END_TPR_ID AND
		E.END_TPL_ID = I.END_TPL_ID AND
		E.END_MUC_ID = I.END_MUC_ID
	)
	BEGIN
		INSERT INTO ENDERECOS(END_APELIDO,END_LOGRADOURO,END_NUMERO,END_CEP,END_OBSERVACAO,END_BAIRRO,END_TPR_ID,END_TPL_ID,END_MUC_ID)
		SELECT I.END_APELIDO, I.END_LOGRADOURO, I.END_NUMERO, I.END_CEP, I.END_OBSERVACAO, I.END_BAIRRO, I.END_TPR_ID, I.END_TPL_ID, I.END_MUC_ID FROM INSERTED I
	END
END;
GO


CREATE TRIGGER TG_VerificarCartao
ON CARTOES
INSTEAD OF INSERT
AS BEGIN
	IF NOT EXISTS(
		SELECT 1 FROM CARTOES C
		JOIN INSERTED I ON
		C.CRT_APELIDO = I.CRT_APELIDO AND
		C.CRT_NUMERO = I.CRT_NUMERO AND
		C.CRT_CVV = I.CRT_CVV AND
		C.CRT_FUNCAO = I.CRT_FUNCAO AND
		C.CRT_BDC_ID = I.CRT_BDC_ID
	)
	BEGIN
		INSERT INTO CARTOES(CRT_APELIDO, CRT_NUMERO, CRT_CVV, CRT_FUNCAO, CRT_BDC_ID)
		SELECT I.CRT_APELIDO, I.CRT_NUMERO, I.CRT_CVV, I.CRT_FUNCAO, I.CRT_BDC_ID FROM INSERTED I
	END
	
END;
GO


CREATE TRIGGER TG_VerificarMarca
ON MARCAS
INSTEAD OF INSERT
AS BEGIN
	IF NOT EXISTS(
		SELECT 1 FROM MARCAS M
		JOIN INSERTED I ON
		M.MRC_NOME = I.MRC_NOME
	)
	BEGIN
		INSERT INTO MARCAS (MRC_NOME) 
		SELECT I.MRC_NOME FROM INSERTED I
	END
END;
GO


CREATE TRIGGER TG_VerificarFornecedor
ON FORNECEDORES
INSTEAD OF INSERT
AS BEGIN
	IF NOT EXISTS(
		SELECT 1 FROM FORNECEDORES F
		JOIN INSERTED I ON
		F.FRD_NOME = I.FRD_NOME
	)
	BEGIN
		INSERT INTO FORNECEDORES (FRD_NOME) 
		SELECT I.FRD_NOME FROM INSERTED I
	END

END;
GO