

CREATE VIEW Vw_DadosUsuario
AS
SELECT * FROM USUARIOS
JOIN GENEROS ON GNR_ID = USU_GNR_ID
JOIN USUARIOS_ENDERECOS ON USEN_USU_ID = USU_ID
JOIN Vw_Endereco ON END_ID = USEN_END_ID
JOIN USUARIOS_CARTOES ON USCT_USU_ID = USU_ID
JOIN Vw_Cartao ON CRT_ID = USCT_CRT_ID
JOIN Vw_Telefone ON TLF_ID = USU_TLF_ID
JOIN TIPOS_USUARIO ON TPU_ID = USU_TPU_ID;
GO

select * from Vw_DadosUsuario;

CREATE VIEW Vw_Endereco
AS
SELECT * FROM ENDERECOS
JOIN TIPOS_LOGRADOURO ON TPL_ID = END_TPL_ID
JOIN TIPOS_RESIDENCIA ON TPR_ID = END_TPR_ID
JOIN MUNICIPIOS ON MUC_ID = END_MUC_ID
JOIN ESTADOS ON EST_ID = MUC_EST_ID
JOIN PAISES ON PAS_ID = EST_PAS_ID;
GO


CREATE VIEW Vw_Cartao
AS
SELECT * FROM CARTOES
JOIN BANDEIRAS_CARTAO ON BDC_ID = CRT_BDC_ID;
GO


CREATE VIEW Vw_Telefone
AS
SELECT * FROM  TELEFONES 
JOIN TIPOS_TELEFONE ON TPT_ID = TLF_TPT_ID;
GO


CREATE VIEW Vw_Produto
AS
SELECT * FROM PRODUTOS
JOIN MARCAS ON MRC_ID = PRD_MRC_ID 
JOIN FORNECEDORES ON FRD_ID = PRD_FRD_ID
JOIN ESTOQUE ON PRD_ID = ETQ_PRD_ID
JOIN TIPOS_PRODUTO ON TPP_ID = PRD_TPP_ID
JOIN GRUPO_PRECIFICACAO ON GRP_ID = PRD_GRP_ID;
GO


CREATE VIEW Vw_Carrinho
AS 
SELECT * FROM CARRINHO
JOIN Vw_Produto ON PRD_ID = CRN_PRD_ID
JOIN USUARIOS ON CRN_USU_ID = USU_ID
GO


CREATE VIEW Vw_Pedido
AS
SELECT * FROM PEDIDOS
JOIN STATUS_PEDIDO ON STP_ID = PDD_STP_ID
JOIN ITENS_PEDIDO ON PDD_ID = IPD_PDD_ID
JOIN Vw_Produto ON PRD_ID = IPD_PRD_ID
JOIN USUARIOS ON USU_ID = PDD_USU_ID
JOIN GENEROS ON GNR_ID = USU_GNR_ID
JOIN Vw_Endereco ON END_ID = PDD_END_ID
JOIN CARTOES_PEDIDOS ON CTPD_PDD_ID = PDD_ID
JOIN Vw_Cartao ON CRT_ID = CTPD_CRT_ID
JOIN Vw_Telefone ON TLF_ID = USU_TLF_ID
JOIN TIPOS_USUARIO ON TPU_ID = USU_TPU_ID
LEFT JOIN CUPONS_PEDIDOS ON CPPD_PDD_ID = PDD_ID
LEFT JOIN CUPONS ON CPN_ID = CPPD_CPN_ID
GO


CREATE VIEW Vw_SolicitacaoTroca
AS
SELECT * FROM SOLICITACOES_TROCA
JOIN Vw_Produto ON SLT_PRD_ID = PRD_ID
JOIN PEDIDOS ON SLT_PDD_ID = PDD_ID
JOIN USUARIOS ON PDD_USU_ID = USU_ID
GO