use EletronicStore;
go

CREATE VIEW Vw_DadosUsuario
AS
SELECT * FROM USUARIOS
JOIN GENEROS ON GNR_ID = USU_GNR_ID
JOIN USUARIOS_ENDERECOS ON USEN_USU_ID = USU_ID
JOIN Vw_Endereco ON END_ID = USEN_END_ID
JOIN USUARIOS_CARTOES ON USCT_USU_ID = USU_ID
JOIN Vw_Cartao ON CRT_ID = USCT_CRT_ID
JOIN Vw_Telefone ON TLF_ID = USU_TLF_ID
JOIN TIPOS_USUARIO ON TPU_ID = USU_TPU_ID;
GO

select * from Vw_DadosUsuario;

CREATE VIEW Vw_Endereco
AS
SELECT * FROM ENDERECOS
JOIN TIPOS_LOGRADOURO ON TPL_ID = END_TPL_ID
JOIN TIPOS_RESIDENCIA ON TPR_ID = END_TPR_ID
JOIN MUNICIPIOS ON MUC_ID = END_MUC_ID
JOIN ESTADOS ON EST_ID = MUC_EST_ID
JOIN PAISES ON PAS_ID = EST_PAS_ID;
GO


CREATE VIEW Vw_Cartao
AS
SELECT * FROM CARTOES
JOIN BANDEIRAS_CARTAO ON BDC_ID = CRT_BDC_ID;
GO


CREATE VIEW Vw_Telefone
AS
SELECT * FROM  TELEFONES 
JOIN TIPOS_TELEFONE ON TPT_ID = TLF_TPT_ID;
GO

select * from Vw_Cartao;